#ifndef OCTOS_FFI_H
#define OCTOS_FFI_H

#pragma once

/* Generated by cbindgen. DO NOT EDIT. Regenerate with the command in crates/octos-ffi/cbindgen.toml. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque runtime handle. Holds the shared pieces (tokio runtime, provider,
// memory) and rebuilds a fresh [`Agent`] per task so a per-task
// `max_iterations` can be honored (the `Agent` config is otherwise fixed at
// construction).
typedef struct OctosRuntime OctosRuntime;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Create a runtime from a JSON config. Returns NULL on error (see
// [`octos_last_error`]); the returned handle must be freed with
// [`octos_runtime_free`].
OctosRuntime *octos_runtime_new(const char *config_json);

// Free a runtime created by [`octos_runtime_new`]. NULL is a no-op.
void octos_runtime_free(OctosRuntime *runtime);

// Run a one-shot task. `brief_json` is `{"prompt": "...", "max_iterations"?:
// N}`. Returns owned JSON `{"output", "iterations", "tokens"}` (free with
// [`octos_string_free`]) or NULL on error.
char *octos_run_task(OctosRuntime *runtime, const char *brief_json);

// Embed `text`. Returns owned JSON `{"embedding": [f32, ...]}` (free with
// [`octos_string_free`]) or NULL on error. Requires the `embed-llama` feature
// and an `embedding_model_path` in the config.
char *octos_embed(OctosRuntime *runtime, const char *text);

// Free a string returned by [`octos_run_task`] / [`octos_embed`]. NULL is a
// no-op. Never call `free(3)` on these; never double-free.
void octos_string_free(char *s);

// Return the thread-local last-error string, or NULL if none. Do NOT free it;
// valid only until the next FFI call on this thread.
const char *octos_last_error(void);

// Return the crate version as a static NUL-terminated string (never freed).
const char *octos_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OCTOS_FFI_H */
